# Tide prompt settings (the author's own: his tide_* variables, set as globals).
# Globals shadow the universal variables, so a fresh home gets this prompt without running `tide configure`;
# `tide configure` still works, but variables set here win over its answers.
set -g tide_aws_bg_color 8A6D2F
set -g tide_aws_color F2EDD8
set -g tide_aws_icon 
set -g tide_character_color 7D8278
set -g tide_character_color_failure BD5636
set -g tide_character_icon ❯
set -g tide_character_vi_icon_default ❮
set -g tide_character_vi_icon_replace ▶
set -g tide_character_vi_icon_visual V
set -g tide_cmd_duration_bg_color 8A6D2F
set -g tide_cmd_duration_color F2EDD8
set -g tide_cmd_duration_decimals 0
set -g tide_cmd_duration_icon 
set -g tide_cmd_duration_threshold 3000
set -g tide_context_always_display false
set -g tide_context_bg_color 3B342B
set -g tide_context_color_default E9C87E
set -g tide_context_color_root BD5636
set -g tide_context_color_ssh 5C6B6F
set -g tide_context_hostname_parts 1
set -g tide_crystal_bg_color F2EDD8
set -g tide_crystal_color 3B342B
set -g tide_crystal_icon 
set -g tide_direnv_bg_color 8A6D2F
set -g tide_direnv_bg_color_denied BD5636
set -g tide_direnv_color F2EDD8
set -g tide_direnv_color_denied F2EDD8
set -g tide_direnv_icon ▼
set -g tide_distrobox_bg_color 7E5647
set -g tide_distrobox_color F2EDD8
set -g tide_distrobox_icon 󰆧
set -g tide_docker_bg_color 5C6B6F
set -g tide_docker_color F2EDD8
set -g tide_docker_default_contexts default colima
set -g tide_docker_icon 
set -g tide_elixir_bg_color 7E5647
set -g tide_elixir_color F2EDD8
set -g tide_elixir_icon 
set -g tide_gcloud_bg_color 5C6B6F
set -g tide_gcloud_color F2EDD8
set -g tide_gcloud_icon 󰊭
set -g tide_git_bg_color 7D8278
set -g tide_git_bg_color_unstable 8A6D2F
set -g tide_git_bg_color_urgent BD5636
set -g tide_git_color_branch F2EDD8
set -g tide_git_color_conflicted F2EDD8
set -g tide_git_color_dirty F2EDD8
set -g tide_git_color_operation F2EDD8
set -g tide_git_color_staged F2EDD8
set -g tide_git_color_stash F2EDD8
set -g tide_git_color_untracked F2EDD8
set -g tide_git_color_upstream F2EDD8
set -g tide_git_icon 
set -g tide_git_truncation_length 24

set -g tide_go_bg_color 7D8278
set -g tide_go_color F2EDD8
set -g tide_go_icon 
set -g tide_java_bg_color 8A6D2F
set -g tide_java_color F2EDD8
set -g tide_java_icon 
set -g tide_jobs_bg_color 3B342B
set -g tide_jobs_color E9C87E
set -g tide_jobs_icon 
set -g tide_jobs_number_threshold 1000
set -g tide_kubectl_bg_color 5C6B6F
set -g tide_kubectl_color F2EDD8
set -g tide_kubectl_icon 󱃾
set -g tide_left_prompt_frame_enabled false
set -g tide_left_prompt_items os pwd git newline character
set -g tide_left_prompt_prefix ''
set -g tide_left_prompt_separator_diff_color 
set -g tide_left_prompt_separator_same_color 
set -g tide_left_prompt_suffix 
set -g tide_nix_shell_bg_color 5C6B6F
set -g tide_nix_shell_color F2EDD8
set -g tide_nix_shell_icon 
set -g tide_node_bg_color 7D8278
set -g tide_node_color F2EDD8
set -g tide_node_icon 
set -g tide_os_bg_color 3B342B
set -g tide_os_color E9C87E
set -g tide_os_icon 
set -g tide_php_bg_color 7E5647
set -g tide_php_color F2EDD8
set -g tide_php_icon 
set -g tide_private_mode_bg_color F2EDD8
set -g tide_private_mode_color 3B342B
set -g tide_private_mode_icon 󰗹
set -g tide_prompt_add_newline_before false
set -g tide_prompt_color_frame_and_connection 9C8B66
set -g tide_prompt_color_separator_same_color C9B896
set -g tide_prompt_icon_connection ·
set -g tide_prompt_min_cols 34
set -g tide_prompt_pad_items true
set -g tide_prompt_transient_enabled true
set -g tide_pulumi_bg_color 8A6D2F
set -g tide_pulumi_color F2EDD8
set -g tide_pulumi_icon 
set -g tide_pwd_bg_color 3B342B
set -g tide_pwd_color_anchors E9C87E
set -g tide_pwd_color_dirs F2EDD8
set -g tide_pwd_color_truncated_dirs C9B896
set -g tide_pwd_icon 
set -g tide_pwd_icon_home 
set -g tide_pwd_icon_unwritable 
set -g tide_pwd_markers .bzr .citc .git .hg .node-version .python-version .ruby-version .shorten_folder_marker .svn .terraform Cargo.toml composer.json CVS go.mod package.json build.zig
set -g tide_python_bg_color 3B342B
set -g tide_python_color 9AA89B
set -g tide_python_icon 󰌠
set -g tide_right_prompt_frame_enabled false
set -g tide_right_prompt_items status cmd_duration context jobs direnv node python rustc java php pulumi ruby go gcloud kubectl distrobox toolbox terraform aws nix_shell crystal elixir zig time
set -g tide_right_prompt_prefix 
set -g tide_right_prompt_separator_diff_color 
set -g tide_right_prompt_separator_same_color 
set -g tide_right_prompt_suffix ''
set -g tide_ruby_bg_color BD5636
set -g tide_ruby_color F2EDD8
set -g tide_ruby_icon 
set -g tide_rustc_bg_color 8A6D2F
set -g tide_rustc_color F2EDD8
set -g tide_rustc_icon 
set -g tide_shlvl_bg_color 7D8278
set -g tide_shlvl_color F2EDD8
set -g tide_shlvl_icon 
set -g tide_shlvl_threshold 1
set -g tide_status_bg_color 3B342B
set -g tide_status_bg_color_failure BD5636
set -g tide_status_color 93988C
set -g tide_status_color_failure F2EDD8
set -g tide_status_icon ✔
set -g tide_status_icon_failure ✘
set -g tide_terraform_bg_color 7E5647
set -g tide_terraform_color F2EDD8
set -g tide_terraform_icon 󱁢
set -g tide_time_bg_color 3B342B
set -g tide_time_color C9B896
set -g tide_time_format '%T'
set -g tide_toolbox_bg_color 7E5647
set -g tide_toolbox_color F2EDD8
set -g tide_toolbox_icon 
set -g tide_vi_mode_bg_color_default 3B342B
set -g tide_vi_mode_bg_color_insert 7D8278
set -g tide_vi_mode_bg_color_replace BD5636
set -g tide_vi_mode_bg_color_visual 8A6D2F
set -g tide_vi_mode_color_default F2EDD8
set -g tide_vi_mode_color_insert F2EDD8
set -g tide_vi_mode_color_replace F2EDD8
set -g tide_vi_mode_color_visual F2EDD8
set -g tide_vi_mode_icon_default D
set -g tide_vi_mode_icon_insert I
set -g tide_vi_mode_icon_replace R
set -g tide_vi_mode_icon_visual V
set -g tide_zig_bg_color 8A6D2F
set -g tide_zig_color F2EDD8
set -g tide_zig_icon 
